"""Supervisor agent: aggregates dimension scores and produces the final scoring result."""

from __future__ import annotations

import logging
import uuid

from pydantic import BaseModel

from calllens.agents.llm import (
    AgentScore,
    KeyMomentRef,
    LLMProvider,
    SupervisorNarrative,
    TimedTranscriptSegmentData,
    TranscriptSegmentData,
    get_llm_provider,
)
from calllens.agents.specialists import FullRubricDimensionData

logger = logging.getLogger(__name__)

# Overall score below this threshold triggers an escalation flag.
_ESCALATION_SCORE_THRESHOLD: int = 60

# Compliance score below this triggers an escalation flag (compliance fail).
_COMPLIANCE_FAIL_THRESHOLD: int = 50

# Confidence factor applied to unsupported scores during weighted aggregation.
# Unsupported dimensions contribute weight × this factor instead of full weight,
# so unreliable scores have reduced influence on the overall result.
_UNSUPPORTED_WEIGHT_FACTOR: float = 0.5


class SupervisorResult(BaseModel):
    """Complete output of the supervisor node — everything Phase 4B needs to persist."""

    overall_score: int
    """Weighted average of dimension scores. Formula documented in _compute_overall_score."""

    dimension_scores_int: dict[str, int]
    """Dimension key -> integer score (0-100) for each scored dimension."""

    escalate_for_review: bool
    """True when any escalation rule fires. See _compute_escalation for the rules."""

    escalation_reason: str | None
    """Human-readable reason for escalation, or None if not escalated."""

    summary: str
    """Concise LLM-generated call summary."""

    key_moments: list[KeyMomentRef]
    """Notable moments with segment references validated against real segments."""

    action_items: list[str]
    """Concrete follow-up actions generated by the supervisor."""

    coaching_note: str
    """Draft coaching note for the agent's manager."""


def _compute_overall_score(
    dimension_scores: dict[str, AgentScore],
    dimensions: list[FullRubricDimensionData],
) -> int:
    """Compute the weighted overall score across all dimensions.

    Formula:
        effective_weight(dim) = dim.weight * (1.0 if is_supported else 0.5)
        overall = sum(score * effective_weight) / sum(effective_weight)

    Unsupported/low-confidence dimensions are down-weighted by 50% rather than
    counted as 0, so a single failed LLM call doesn't crater the overall score.

    Returns 0 if no dimensions were scored.

    Args:
        dimension_scores: Map of dimension key -> AgentScore.
        dimensions: Full dimension list with weights.

    Returns:
        Integer overall score clamped to [0, 100].
    """
    total_weighted = 0.0
    total_weight = 0.0

    for dim in dimensions:
        key = dim["key"]
        if key not in dimension_scores:
            continue
        agent_score = dimension_scores[key]
        factor = 1.0 if agent_score.is_supported else _UNSUPPORTED_WEIGHT_FACTOR
        effective_weight = dim["weight"] * factor
        total_weighted += agent_score.score * effective_weight
        total_weight += effective_weight

    if total_weight == 0.0:
        return 0

    return max(0, min(100, round(total_weighted / total_weight)))


def _compute_escalation(
    dimension_scores: dict[str, AgentScore],
    overall_score: int,
) -> tuple[bool, str | None]:
    """Determine whether the call should be escalated for human review.

    Escalation rules (any one fires escalation):
    1. compliance score < _COMPLIANCE_FAIL_THRESHOLD (50) — regulatory risk
    2. overall_score < _ESCALATION_SCORE_THRESHOLD (60) — poor overall performance
    3. sentiment_empathy score < 50 AND outcome score < 50 simultaneously —
       agent was cold/negative AND the call ended poorly

    Args:
        dimension_scores: All per-dimension AgentScore results.
        overall_score: Weighted overall score from _compute_overall_score.

    Returns:
        Tuple of (escalate_for_review: bool, escalation_reason: str | None).
    """
    reasons: list[str] = []

    compliance = dimension_scores.get("compliance")
    if compliance is not None and compliance.score < _COMPLIANCE_FAIL_THRESHOLD:
        reasons.append(
            f"Compliance failure (score={compliance.score} < {_COMPLIANCE_FAIL_THRESHOLD})"
        )

    if overall_score < _ESCALATION_SCORE_THRESHOLD:
        reasons.append(f"Low overall score ({overall_score} < {_ESCALATION_SCORE_THRESHOLD})")

    sentiment = dimension_scores.get("sentiment_empathy")
    outcome = dimension_scores.get("outcome")
    if (
        sentiment is not None
        and outcome is not None
        and sentiment.score < 50
        and outcome.score < 50
    ):
        reasons.append("Negative sentiment combined with poor call outcome")

    if reasons:
        return True, "; ".join(reasons)
    return False, None


def _validate_key_moments(
    moments: list[KeyMomentRef],
    valid_segment_ids: set[uuid.UUID],
) -> list[KeyMomentRef]:
    """Drop key_moment entries whose segment_id is not in valid_segment_ids.

    Args:
        moments: LLM-generated list of key moments.
        valid_segment_ids: Set of segment UUIDs from the actual transcript.

    Returns:
        Filtered list with only valid segment references.
    """
    return [m for m in moments if m.segment_id in valid_segment_ids]


async def run_supervisor(
    dimension_scores: dict[str, AgentScore],
    dimensions: list[FullRubricDimensionData],
    segments: list[TimedTranscriptSegmentData],
    provider: LLMProvider | None = None,
) -> SupervisorResult:
    """Run the supervisor: aggregate scores, apply escalation rules, generate narrative.

    Deterministic parts (no LLM):
    - overall_score from weighted average (see _compute_overall_score)
    - escalation flag and reason (see _compute_escalation)

    LLM-generated parts (via provider.generate_narrative):
    - summary, key_moments, action_items, coaching_note

    Key_moment segment_ids are validated against real segments; invalid ones are dropped.

    Args:
        dimension_scores: All per-dimension AgentScore results from specialist nodes.
        dimensions: Full rubric dimension list with weights.
        segments: Timed transcript segments (used for context and key_moment validation).
        provider: LLM provider; defaults to get_llm_provider().

    Returns:
        A SupervisorResult with all fields populated.
    """
    if provider is None:
        provider = get_llm_provider()

    overall_score = _compute_overall_score(dimension_scores, dimensions)
    escalate, escalation_reason = _compute_escalation(dimension_scores, overall_score)

    valid_ids: set[uuid.UUID] = {s["id"] for s in segments}

    # Build base segments for LLM call (drop timing fields)
    base_segments: list[TranscriptSegmentData] = [
        TranscriptSegmentData(
            id=s["id"],
            sequence=s["sequence"],
            text=s["text"],
            speaker=s["speaker"],
        )
        for s in segments
    ]

    scores_summary = "\n".join(
        f"  {key}: {score.score}/100 (confidence={score.confidence:.2f}, "
        f"supported={score.is_supported})"
        for key, score in dimension_scores.items()
    )
    system = (
        "You are a call quality supervisor synthesising scoring results into actionable feedback.\n"
        "You will receive scored dimension results and the full call transcript.\n"
        "Produce a concise summary, identify key moments (cite exact segment IDs), "
        "list concrete action items for the agent, and write a coaching note for the manager.\n"
        "Only reference segment IDs that appear in the transcript."
    )
    lines = [
        f"Overall score: {overall_score}/100",
        f"Escalated: {escalate}" + (f" — {escalation_reason}" if escalation_reason else ""),
        "",
        "Dimension scores:",
        scores_summary,
        "",
        "Transcript:",
    ]
    for seg in base_segments:
        lines.append(f"[{seg['id']}] seq={seg['sequence']} speaker={seg['speaker']}: {seg['text']}")
    user = "\n".join(lines)

    narrative: SupervisorNarrative = await provider.generate_narrative(system, user, base_segments)

    validated_moments = _validate_key_moments(narrative.key_moments, valid_ids)

    return SupervisorResult(
        overall_score=overall_score,
        dimension_scores_int={key: score.score for key, score in dimension_scores.items()},
        escalate_for_review=escalate,
        escalation_reason=escalation_reason,
        summary=narrative.summary,
        key_moments=validated_moments,
        action_items=narrative.action_items,
        coaching_note=narrative.coaching_note,
    )
