"""StorageBackend Protocol — the contract all storage implementations must satisfy."""

from collections.abc import AsyncGenerator
from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    """Abstract interface for audio file storage."""

    async def save(self, data: bytes, key: str) -> str:
        """Persist bytes under the given key, returning the key.

        Args:
            data: Raw file bytes to persist.
            key: Storage key (path-like, generated by the upload handler).

        Returns:
            The key used to store the file.
        """
        ...

    def open_stream(
        self, key: str, *, start: int = 0, end: int | None = None
    ) -> AsyncGenerator[bytes, None]:
        """Yield file bytes, optionally constrained to a byte range.

        Args:
            key: Storage key of the file to stream.
            start: First byte offset (inclusive, default 0).
            end: Last byte offset (exclusive). None means stream to EOF.

        Yields:
            Chunks of file bytes.
        """
        ...

    async def file_size(self, key: str) -> int:
        """Return the total byte size of the stored file.

        Args:
            key: Storage key of the file.

        Returns:
            File size in bytes.
        """
        ...

    async def delete(self, key: str) -> None:
        """Remove the stored file.

        Args:
            key: Storage key of the file to delete.
        """
        ...

    async def exists(self, key: str) -> bool:
        """Check whether a file exists.

        Args:
            key: Storage key to probe.

        Returns:
            True if the file exists.
        """
        ...
